default_platform :ios

platform :ios do
  skip_docs

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  
  desc "Deploys Atlas Messenger to HockeyApp"
  lane :deploy do
    cert
    sigh
    gym(
      use_legacy_build_api: true
    )
    hockey
  end
end

